### ISSUE TITLE
Extension doesn't finish analysing

### ISSUE THREAD

**Issue by AntWard** [stefanwalther/sense-extension-governance#12]
Hi Stefan, I tried the app on both server and desktop and get the same issue, it just hangs and doesn't finish analysing. I thought it may be a particular app or extension, so I tried the desktop version with no apps other than one with just this extension in it, and with no other extensions. The result was the same. I'm not really sure what else to try and am very keen to see this working as it would be extremely useful for me. Can you offer any suggestions? Cheers, Ant

**Comment by stefanwalther** [comment]
Hi, which version of Qlik Sense are you using?

**Comment by AntWard** [comment]
Hi Stefan, desktop is 3.0.1 and server is 3.1

**Comment by AntWard** [comment]
Also I just upgraded both desktop and server to 3.1.1 and tried again but got the same result. Cheers

**Comment by bennyxlin** [comment]
Hi Stefan,  I just tested sense-extension-governance on my QS Desktop v3.1 SR3 with two apps on the hub - the Consumer_Sales app and this test app.  I confirmed what Ant described, the test sheet stuck at "Analyzing Consumer_Sales.qvf", never finished analyzing.  I too think your extension could be very helpful to many Qlik Sense users, in particular, those who manage a large QS site with many apps and extensions.  Hope you could get it to work with QS 3.1.  Thanks.

**Comment by bchastain** [comment]
I too am running into the same problem

**Comment by meritxell-almenara** [comment]
Hello,

I've the same issue, either in qlik sense 3.1 and 3.2.

Meri
