### ISSUE TITLE
Not able to fetch details via externsion

### ISSUE THREAD

**Issue by saikatjana2309** [stefanwalther/sense-extension-governance#16]
We are facing below error every time we ran the extension in Qliksense Server with Qliksense Sep 2017, Patch2.

We have the server with virtual proxy. Please let me know if it will work in our configutaion.

![image](https://user-images.githubusercontent.com/34538702/38985712-cb28872e-43e7-11e8-8859-841065ea2ad7.png)

I can confirm it is not a connection issue or timeout as it looks in the error

**Comment by Asparagus11** [comment]
Hi, I have the same error on Juneb Release 2018

**Comment by simonaubertbd** [comment]
Hello,

I have exactly the same issue with Feb 2019. @stefanwalther : do you know where it comes from ?

**Comment by simonaubertbd** [comment]
i have some reasons to believe it's here 
![image](https://user-images.githubusercontent.com/46959192/59762550-c6878d00-9297-11e9-9559-f79aeb944246.png)
